// Actions types
export const VALIDATE_USER = 'VALIDATE_USER';
export const USER_VALIDATION_SUCCESS = 'USER_VALIDATION_SUCCESS';
export const USER_VALIDATION_FAILED = 'USER_VALIDATION_FAILED';
export const USER_LOGOUT = 'USER_LOGOUT';
export const STORE_COUNTRIES = 'STORE_COUNTRIES';
